import { getLocale } from '@/lib/request-locale';
import { translate } from '@/lib/i18n';
import { LocalizedLink as Link } from '@/components/localized-link';
import { notFound } from 'next/navigation';
import { articles } from '@/lib/content';
import { getArticles } from '@/lib/content-tr';
import { Label, Motif } from '@/components/site';
export function generateStaticParams(){return articles.map(a=>({slug:a.slug}))}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const locale=await getLocale();return {title:getArticles(locale).find(a=>a.slug===slug)?.title||translate(locale,'note not found')}}
export default async function Article({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const locale=await getLocale();const t=(text:string)=>translate(locale,text);const a=getArticles(locale).find(a=>a.slug===slug);if(!a)notFound();return <main id="main" className="shell page-main"><Link locale={locale} className="small-link" href="/thinking">{t("back to the notebook")}</Link><div className="article-title"><Label>{t(a.category)} / {t('note')} {a.number}</Label><h1>{a.title}</h1><p>{a.summary}</p><div className="article-byline"><span>{t("by barış")}</span><span>{a.game}</span><span>{a.readTime}</span></div></div><div className="sample-banner">{t("sample analysis / Illustrative content for v0.1. No experiment has been run; these are hypotheses, not research findings.")}</div><div className="article-layout"><aside><Label>{t("in this note")}</Label><nav aria-label={t("Article contents")}>{a.sections.map((s,i)=><a key={s.title} href={`#section-${i}`}>{s.title}</a>)}</nav></aside><article className="article-body"><Motif locale={locale} kind={a.motif} visual={a.visual} large/>{a.sections.map((s,i)=><section id={`section-${i}`} key={s.title}><Label>0{i+1}</Label><h2>{s.title}</h2><p>{s.body}</p></section>)}<div className="article-end"><Label>{t("keep questioning")}</Label><p>{t("A working thought, open to a better explanation.")}</p><Link locale={locale} href="/experiments" className="small-link">{t("see the experiment notebook")}</Link></div></article></div></main>}
