export const topics = ['all', 'teardowns', 'experiments', 'observations', 'game psychology', 'growth', 'monetization', 'retention', 'game economy', 'live ops'] as const;
export type Topic = typeof topics[number];
export type Article = { slug: string; title: string; category: Topic; game: string; summary: string; readTime: string; number: string; motif: string; sections: { title: string; body: string }[] };
export const articles: Article[] = [
  { slug: 'royal-match-first-ten-minutes', title: "why royal match’s first 10 minutes work", category: 'teardowns', game: 'royal match', summary: 'A closer look at early wins, quiet teaching, and the momentum that makes one more level feel natural.', readTime: '6 min read', number: '01', motif: 'match', sections: [
    { title: 'context', body: 'The first session has a difficult job: teach the rules without making learning feel like work. This illustrative teardown looks at how a puzzle game might turn a new player into a confident player. These are sample interpretations, not verified findings from Royal Match telemetry.' },
    { title: 'observation', body: 'Early levels appear to make the next action easy to understand. A clear goal, a small board, and frequent feedback reduce the number of decisions a player has to make at once. Progress feels visible before the player has mastered every mechanic.' },
    { title: 'why it matters', body: 'A player who feels capable has a reason to continue. My working assumption is that early confidence matters as much as the reward itself: a win tells the player “I understand this.” The interesting question is which part of that confidence actually drives a second session.' },
    { title: 'hypothesis', body: 'If the first three levels introduce one mechanic at a time and reward independent discovery, more new players will complete the onboarding sequence than with a longer, instruction-heavy tutorial.' },
    { title: 'proposed experiment', body: 'Randomly assign eligible new players to the current tutorial or a version with shorter prompts and one mechanic per level. Keep rewards and difficulty comparable. Measure both groups over seven days, and set the sample size and stopping rule before launching.' },
    { title: 'success metric', body: 'Primary: the share of new players completing level 10 in their first session. Secondary: day-one return rate. Guardrails: first-session abandonment, repeated failed attempts, and accidental purchases. A faster completion time alone would not establish a better experience.' },
    { title: 'possible risk', body: 'Fewer instructions could leave some players confused, particularly those unfamiliar with match-three games. Segment results by prior puzzle experience where consented data is available, and watch for a benefit that disappears after the first session.' },
    { title: 'takeaway', body: 'Good onboarding may be less about explaining the entire game and more about helping someone feel ready for their next move. The next step is to test that idea, rather than treat it as a conclusion.' }
  ] },
  { slug: 'progression-and-motivation', title: 'what makes a progression system addictive?', category: 'game psychology', game: 'across games', summary: 'Visible progress, unfinished goals, and the difference between wanting to return and feeling obliged to.', readTime: '4 min read', number: '02', motif: 'steps', sections: [{title:'observation',body:'A progress bar makes an abstract goal visible. This sample note asks whether the distance to the next milestone changes how players choose their next session.'},{title:'hypothesis',body:'Smaller, meaningful milestones could improve voluntary return rates. More milestones alone may only add noise.'},{title:'next question',body:'How would we distinguish healthy motivation from pressure? Measure satisfaction alongside repeat sessions and offer players meaningful stopping points.'}] },
  { slug: 'fair-game-economy', title: 'what makes a game economy feel fair?', category: 'game economy', game: 'across games', summary: 'Looking beyond prices to predictability, effort, and the promises an economy makes.', readTime: '5 min read', number: '03', motif: 'coins', sections: [{title:'observation',body:'Two rewards with the same value can feel different when their rules differ. Predictability may shape perceived fairness as much as generosity.'},{title:'hypothesis',body:'Showing reward odds and a clear path to earning currency could improve perceived fairness without changing reward value.'},{title:'proposed experiment',body:'Compare two transparent explanations with a comprehension check and a voluntary fairness survey. Monitor spending regret as a guardrail.'}] },
  { slug: 'losing-and-retention', title: 'why losing can sometimes improve retention', category: 'retention', game: 'puzzle games', summary: 'A question about near misses, achievable challenges, and when friction stops being useful.', readTime: '3 min read', number: '04', motif: 'steps', sections: [{title:'context',body:'This is a sample research question, not a claim that making games harder improves retention.'},{title:'hypothesis',body:'A recoverable setback might make a later win more meaningful, provided players feel the outcome is understandable and the next attempt is achievable.'},{title:'possible risk',body:'Frustration can overwhelm motivation. Track abandonment and player sentiment rather than optimizing retries in isolation.'}] }
];
export const experiments = [
 {id:'01',slug:'status-or-rewards',title:'status or rewards?',question:'Do players value public recognition more than extra currency?',hypothesis:'A visible contribution badge could encourage more repeat participation than an equally costly currency reward.',setup:'Compare recognition and currency rewards in an opt-in community challenge, with randomized groups and equal eligibility.',metric:'Repeat participation within 7 days; satisfaction as a guardrail.',lesson:'Distinguish lasting motivation from a short-lived novelty effect.',tag:'incentives'},
 {id:'02',slug:'small-groups',title:'a smaller circle, a stronger reason to return?',question:'Do small groups create stronger retention than large communities?',hypothesis:'Being noticed by a familiar group could make a return visit feel more meaningful.',setup:'Compare small teams and a larger shared group with the same activities and rewards.',metric:'Week-two return rate; belonging and moderation burden.',lesson:'Group size may matter less than the quality of interaction.',tag:'social mechanics'},
 {id:'03',slug:'comeback',title:'a better way back',question:'Can a gentler comeback mechanic help lapsed players?',hypothesis:'A short catch-up goal could reduce the overwhelm of returning after a break.',setup:'Offer returning players a focused goal or the standard home screen; keep rewards equivalent.',metric:'Second session within 72 hours; task abandonment.',lesson:'Returning should feel possible before it feels rewarding.',tag:'retention'}
];
